# Change these first
owner: StartUpNationLabs # Your GitHub organization or username, where this repository lives
repo: KubernetesUpptime # The name of this repository

sites:
  - name: Minio API
    url: https://api.minio-main.storage.apoorva64.com/minio/health/live
  - name: Grafana 
    url: https://grafana.monitoring.apoorva64.com
  - name: Harbor
    url: https://harbor.devops-tools.apoorva64.com
  - name: Auth
    url: https://keycloak.auth.apoorva64.com
  - name: OpenWebUi
    url: https://open-webui.ai.apoorva64.com
  - name: React Flight Tracker
    url: https://react-flight-tracker.apoorva64.com
  - name: React Flight Tracker Dev
    url: https://react-flight-tracker.dev.apoorva64.com
  - name: Sonarqube
    url: https://sonarqube.devops-tools.apoorva64.com
  - name: Weave GitOps
    url: https://weave-gitops.devops-tools.apoorva64.com
  - name: RickRoll
    url: https://yes.apoorva64.com
  - name: Kiali (Istio UI)
    url: https://kiali.service-mesh.apoorva64.com/kiali/console
    

status-website:
  baseUrl: /KubernetesUpptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KubernetesUpptime
  introTitle: "UppTime for services on the kubernetes cluster"
  introMessage: Status page for the infrastructure services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
